### ISSUE TITLE
SKOS - Simple Knowledge Organization System

### ISSUE THREAD

**Issue by salgo60** [salgo60/SkansenWikidata#11]
Ett sätt att koppla ihop olika domäner är att använda [SKOS](https://en.wikipedia.org/wiki/Simple_Knowledge_Organization_System)

**Tanke**: Att ha SKOS mellan WIkidata och Skansens kulturnav 

Exempel: [Q10416122#P1248](https://www.wikidata.org/wiki/Q10416122#P1248)
* där **typ av mappning** = [Property:P4390](https://www.wikidata.org/wiki/Property:P4390)
   * som kan ha 
       * [nära matchning](https://www.wikidata.org/wiki/Q39893184) / [Q39893184](https://www.wikidata.org/wiki/Q39893184)
       * [exakt träff](https://www.wikidata.org/wiki/Q39893449) / [Q39893449](https://www.wikidata.org/wiki/Q39893449)
       * [related match](https://www.wikidata.org/wiki/Q39894604) / [Q39894604](https://www.wikidata.org/wiki/Q39894604)
       * [bred träff](https://www.wikidata.org/wiki/Q39894595) / [Q39894595](https://www.wikidata.org/wiki/Q39894595)
       * [smal träff](https://www.wikidata.org/wiki/Q39893967) / [Q39893967](https://www.wikidata.org/wiki/Q39893967)
       
<img width="921" alt="image" src="https://user-images.githubusercontent.com/14206509/187052197-08339843-861d-493d-9bed-6b16c3faf99a.png">

<img width="431" alt="image" src="https://user-images.githubusercontent.com/14206509/187052243-efb57476-810e-414e-a12f-c5069105d8eb.png">

### Är en byggnad och miljö lika breda begrepp?
@AnnaKarinSkansen hur uppfattar du Skansens museala miljöer jämfört med en byggnad där det bara finns en byggnad som det kopplas till är det samma begrepp eller är miljön "bredare"

* **bred träff** [Q39894595](https://www.wikidata.org/wiki/Q39894595?uselang=sv) "_konceptet som värdet pekar på är smalare än angivet Wikidata-objekt_"
* **smal träff** [Q39893967](https://www.wikidata.org/wiki/Q39893967?uselang=sv) "_konceptet som värdet pekar på är bredare än angivet Wikidata-objekt_" 
* **exakt träff** [Q39893967](https://www.wikidata.org/wiki/Q39893449?uselang=sv) "_använt för att länka ihop objekt för att visa att de med största sannolikhet kan användas utbytbart_"
* **nära matchning** [Q39893184](https://www.wikidata.org/wiki/Q39893184?uselang=sv) "_[SKOS relation](https://www.w3.org/TR/skos-reference) (för användning med [P4390](https://www.wikidata.org/wiki/Property:P4390?uselang=sv)): två koncept som är tillräckligt lika så att de kan användas utbytbart i många tillämpningar och scheman. Denna länk är inte tänkt att vara [transitiv](https://sv.wikipedia.org/wiki/Transitiv_relation)_"

ex. [Q113625322#P361](https://www.wikidata.org/wiki/Q113625322?uselang?sv#P361)
* [Tottieska gården, Skansen (Museal byggnad)](https://kulturnav.org/89e33cb6-2195-4d5c-9391-ede85d6cc1ef)
* [Tottieska gården, Skansen (Museal byggnadsmiljö)](https://kulturnav.org/67b54f07-1507-4128-bd2a-8d0767cf1210)

<img width="905" alt="image" src="https://user-images.githubusercontent.com/14206509/187102159-ef20ce4d-60e6-482d-836a-96a47e4e04c0.png">

### medans andra kanske är exakt träff

**Comment by AnnaKarinSkansen** [comment]
Intressant, jag uppfattar byggnader som en "snävare" nivå än miljöer eftersom en miljö kan bestå av en eller flera byggnader och en byggnad kan ingå i en miljö men även i sig själv utgöra hel miljö.

**Comment by salgo60** [comment]
Stänger denna 

@AnnaKarinSkansen Håller med jag började skriva på en fundering vilka WD egenskaper som kan finnas på en miljö respektive en byggnad
* om vi som i [#issuecomment-1229178145](https://github.com/salgo60/SkansenWikidata/issues/2#issuecomment-1229178145)  kopplar en punkt hos Google Map kopplar vi den till miljön eller till byggnaden samma med Open Street Map
* kan en bild avbilda ett koncept eller är det en byggnad?

**Tror det är en nyttig övning att skapa massa praktiska exempel och fundera över**

* i Wikidata har vi massa utmaningar och där försöker man nu beskriva vilka egenskaper olika objekt kan ha exempel som jag gjort med Runstenar hos Litteraturbanken [EntitySchema:E290](https://www.wikidata.org/wiki/EntitySchema:E290)

<img width="983" alt="image" src="https://user-images.githubusercontent.com/14206509/187173928-9845588a-db0b-44c8-8365-d52638eced1f.png">

* [ ] skapa [entity scheman](https://www.wikidata.org/wiki/Wikidata:WikiProject_Schemas) 
   * [ ] entity scheman för Museum miljöer
   * [ ] entity scheman för Museum byggnad

**Comment by salgo60** [comment]
Hur Ikea jobbar med en kunskapsgraf och SKOS - [presentation](https://zenodo.org/record/6501670/files/Increasing%20Knowledge%20Modeling%20Capabilities%20To%20Build%20The%20IKEA%20Knowledge%20Graph%20-%20Katariina%20Kari.pptx?download=1)

<img width="993" alt="image" src="https://user-images.githubusercontent.com/14206509/190060479-b877ab29-8762-4257-853c-2d986e8f934e.png">

**Comment by AnnaKarinSkansen** [comment]
Tack för bra info. kan ev. vara av intresse att kika på i samband med det kompetensutvecklingsprojekt (inom dig) som CMS o RAÄ jobbar med. :-)

**Comment by salgo60** [comment]
@AnnaKarinSkansen uppdatera mig gärna om ni lyckas "sälja in" begreppet museala miljöer hos fler museer.... och om det finns flera som har samma museala miljöer eller **SKOS smalare/bredare**

Man skulle kunna tänka sig att ett statar museum skulle ha en bredare repertuar än vad Statargården på Skansen kan visa upp och vice versa 

* Statare [graf](https://w.wiki/5hop)

<img width="934" alt="image" src="https://user-images.githubusercontent.com/14206509/190411553-83276659-2141-4791-a48d-5bcce692e302.png">

**Comment by salgo60** [comment]
Fundering om [OSM <-> Wikidata skall ha SKOS](https://community.openstreetmap.org/t/persistent-and-stable-identifiers/6819/55?u=salgo60)

[<img width="1215" alt="image" src="https://user-images.githubusercontent.com/14206509/209811830-60082805-8b01-431b-94f1-3068708f8df4.png">](https://community.openstreetmap.org/t/persistent-and-stable-identifiers/6819/55?u=salgo60)
