### ISSUE TITLE
Grafer Wikidata med EasyQuery

### ISSUE THREAD

**Issue by salgo60** [salgo60/SkansenWikidata#9]
**Att göra:** Installera **Easy Query** på Anna Karins Wikidata konto

* [Video om att aktivera Easy Query](https://youtu.be/cY1C2VqIOpg)

<img width="746" alt="image" src="https://user-images.githubusercontent.com/14206509/187018021-cdfb8fab-bb49-4a1a-a282-c2ddf2c0f508.png">

1. Logga in på Wikidata
2. Om du kör svenska gå till [Inställningar Finesser](https://www.wikidata.org/wiki/Special:Preferences#mw-prefsection-gadgets)
3. Leta reda på raden enligt ovan med **EasyQuery** och klicka i det valet
4. Spara

--> nu finns på alla WIkidata objekt **....** som skapar denna fråga det finns även efter dom olika egenskaperna punkter som skapar olika frågor...

A) Bäst är att i höger kanten välja **Link** så man får en "**kort url**" som man sedan klistrar in i webläsaren ex. https://w.wiki/5cxq

<img width="827" alt="image" src="https://user-images.githubusercontent.com/14206509/187018331-e8e9d3c1-86c9-4178-b14d-aa34d9ff06d8.png">

<img width="827" alt="image" src="https://user-images.githubusercontent.com/14206509/187018357-c7805267-8aca-4089-80ba-44c77456f7e6.png">

B) Klistrar man in länken i webläsaren kan man även välja **INCOMMING** länkar ex. testa med https://w.wiki/5cxq

<img width="827" alt="image" src="https://user-images.githubusercontent.com/14206509/187018415-30c28716-d687-4fe1-910a-342b612774e1.png">

Misc
* den kod som körs [MediaWiki:Gadget-EasyQuery.js](https://www.wikidata.org/wiki/MediaWiki:Gadget-EasyQuery.js)

**Comment by AnnaKarinSkansen** [comment]
Tusen tack! Nu har jag fixat EasyQuery och börjar experimentera lite. :-)

**Comment by salgo60** [comment]
Då stänger vi denna 

Skrik till om det är något mera jag är inne i stan idag om jag skall titta förbi.... jag skulle vilja visa dig hur vi arbetar med [iNaturalist](https://www.inaturalist.org/home)
* där kan du ta en bild med [deras app](https://apps.apple.com/us/app/inaturalist/id421397028) 
* en eller flera anger då vilken art bilden föreställer
* i Wikipedia har vi deras taxa i [Property:P3151](https://www.wikidata.org/wiki/Property:P3151) --> att 829 000 arter i Wikidata har samma som vad arten heter i iNaturalist
* saknar vi en bild i Wikipedia på en art kan vi med ett klick söka hos iNaturalist via deras API efter om dom
   * har en bild på arten
   * om det finns en bild där flera har sagt vilken art det är dvs. [research grade](https://edis.ifas.ufl.edu/publication/UW458#:~:text=iNaturalist%20separates%20observations%20into%20two,must%20meet%20four%20initial%20criteria.)
   * om bilden har en frilicens
Video där jag visar iNaturalist [detta vid 8:10](https://youtu.be/8FGFc5rljhc?t=510)och vid [11:30](https://youtu.be/8FGFc5rljhc?t=699) hämtar jag en bild på **Skatan** tagen 2 dagar innan i Liverpool

**Jag tycker ni borde ha som en vision** att står jag på t.ex. ett Museum koncept i Wikipedia så borde jag kunna med ett klick hitta alla bilder hos alla museer som handlar om detta museum koncept....

* anledingen att det fungerar så bra med iNaturlist är att dom jobbar proffsigt med API; har strukturerad data och att vi har samma som Wikidata <-> iNaturalist det vi kallar **[semantisk interoperabilitet](https://sv.wikipedia.org/wiki/Semantisk_interoperabilitet)**

**Comment by AnnaKarinSkansen** [comment]
Tackar, hinner tyvärr inte jobba mer med detta idag men vi höres framöver. 😊

//AK

Från: Magnus Sälgö ***@***.***>
Skickat: den 29 augusti 2022 11:36
Till: salgo60/SkansenWikidata ***@***.***>
Kopia: Anna-Karin Nilsson Stål ***@***.***>; Assign ***@***.***>
Ämne: Re: [salgo60/SkansenWikidata] Grafer Wikidata med EasyQuery (Issue #9)


Då stänger vi denna

Skrik till om det är något mera jag är inne i stan idag om jag skall titta förbi.... ja skulle vilja visa dig hur vi arbetar med iNaturalist<https://www.inaturalist.org/home>

  *   där kan du ta en bild med deras app<https://apps.apple.com/us/app/inaturalist/id421397028>
  *   en eller flera anger då vilken art bilden föreställer
  *   i Wikipedia har vi deras taxa i Property:P3151<https://www.wikidata.org/wiki/Property:P3151> --> att 829 000 arter i Wikidata har samma som vad areten heter i iNaturalist
  *   saknar vi en bild i Wikipedia på en art kan vi med ett klick söka hos iNaturalist via deras API efter om dom
     *   har en bild på arten
     *   om det finns en bild där flera har sagt vilken art det är dvs. research grade<https://edis.ifas.ufl.edu/publication/UW458#:~:text=iNaturalist%20separates%20observations%20into%20two,must%20meet%20four%20initial%20criteria.>
     *   om bilden har en frilicens
Video där jag visar iNaturalist detta vid 8:10<https://youtu.be/8FGFc5rljhc?t=510>och vid 11:30<https://youtu.be/8FGFc5rljhc?t=699> hämtar jag en bild på Skatan tagen 2 dagar innan i Liverpool

Jag tycker ni borde ha som en vision att står jag på t.ex. ett Museum koncept i Wikipedia så borde jag kunna med ett klick hitta alla bilder hos alla museer som handlar om detta museum koncept....
